#配置文件加载顺序 yml-->yaml-->properties 后加载文件属性覆盖先加载文件属性
projectName: springboot-qulick

server:
  port: 8080
  servlet:
    context-path: /dome

student:
  one:
    name: 张三
    age: 18
    # ${property name}获取配置文件指定属性名对应值
    toString: ${student.one.name}--${student.one.age}

students:
  - name: 张三
    age: 18
  - name: 李四
    age: 19

# DataSource Config
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521/orcl
      username: scott
      password: 123456
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
  #JPA Configuration
  jpa:
    database: oracle
    hibernate:
      #每次启动实体与表的映射处理
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    #方言设置
    database-platform: org.hibernate.dialect.Oracle10gDialect
  redis:
    #Reis cluster Config
#    cluster:
#      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
    #数据库索引，默认0 初始化后不能修改库
    database: 0
#    jedis:
#      pool:
#        #连接池最大连接数（负值标识没有限制）
#        max-active: 300
#        #最大堵塞时间（负值标识没有限制）单位ms
#        max-idle: -1
#        #最大空闲连接数
#        max-wait: 100
#        #最小空闲连接数
#        min-idle: 20
    #连接redis超时时间 单位ms
    timeout: 6000
    #Reis Config
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    cache: false #关闭缓存，默认true
    prefix: classpath:/templates/
    suffix: .html

#springboot 集成mybaits
mybatis:
  #mybatis映射文件查找路径
  mapper-locations: classpath:mapper/*Mapper*.xml
  #pojo类别名扫描包路径
  type-aliases-package: com.zhenglt.springboot.pojo




